# Generated by Django 2.2.12 on 2020-04-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loaisp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_l', models.CharField(blank=True, max_length=50, verbose_name='Mã Loại')),
                ('Ten_l', models.CharField(blank=True, max_length=50, verbose_name='Tên Loại')),
                ('Mo_ta', models.TextField(verbose_name='Mô Tả')),
                ('Trang_thai', models.BooleanField(default=True, verbose_name='Trạng Thái')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_sp', models.CharField(max_length=10, verbose_name='Mã Sản Phẩm')),
                ('Ten_sp', models.CharField(blank=True, max_length=50, verbose_name='Tên Sản Phẩm')),
                ('Mo_ta', models.TextField(verbose_name='Mô Tả')),
                ('Gia_nhap', models.IntegerField(blank=True, default=0, verbose_name='Giá Nhập')),
                ('Trang_thai', models.BooleanField(default=True, verbose_name='Trạng Thái')),
                ('Anh', models.ImageField(upload_to='media')),
                ('Loai_sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Loaisp')),
            ],
        ),
        migrations.CreateModel(
            name='SPBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mo_ta', models.SmallIntegerField(choices=[(1, 'Đang Sale 10 %'), (2, 'Đang giảm mạnh'), (3, 'Đang Sale 50 %')], default=2, verbose_name='Mô Tả')),
                ('Gia_ban', models.IntegerField(blank=True, default=200000, verbose_name='Giá Bán')),
                ('Gia_sale', models.IntegerField(default=150000, verbose_name='Giá Sale')),
                ('Hang_ton', models.IntegerField(default=100, verbose_name='Hàng Tồn')),
                ('Trang_thai', models.BooleanField(default=True, verbose_name='Trạng Thái')),
                ('Loai_sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Loaisp')),
                ('San_Pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SanPham')),
            ],
        ),
    ]
